### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by zormit**
Updated the notebooks to be compatible with python 3. This shouldn't break compatibility with Python 2 as I only changed `print` statements to functions and a `xrange` to `range`. I didn't test it on Python 2 though, that's maybe something you might want to do.

Also the Backpropagation notebook was in an older ipython notebook format, which I updated to the latest (jupyter v4) format. I did not really check the source, just followed the automatic conversion and commited it.

### CODE REVIEW

**Comment by craffel** [comment]
Thanks for this, but I believe we need a `from __future__ import print_function`, don't we?  I can also go ahead and update the backpropagation notebook to the latest version, if you just want to rebase against master after.

**Comment by zormit** [comment]
Thanks for your answer on this. 

So, I just tested the stuff in python 2, all seems to work. To ensure, that no one introduces more `print` statements instead of functions you're right, it makes sense to do this import from `__future__`. I just added it.

I was a bit pragmatic there. In fact, to be very clean, it would be necessary to import a lot more from `__future__`, like explained in http://python-future.org.

There seems to be also a tool to convert notebooks https://gist.github.com/takluyver/c8839593c615bb2f6e80, which I didn't try.

Regarding rebasing: We can be very clean here in git history and notebook metadata, but is that worth the effort?

**Comment by craffel** [comment]
>  I just added it.

Thanks.

> Regarding rebasing: We can be very clean here in git history and notebook metadata, but is that worth the effort?

Yes, always!  Just updated.  I can handle the rebasing and merging if you'd prefer.

**Comment by zormit** [comment]
ok, just did the rebasing.

Question on the side, regarding clean git history: I did now update my branch forcefully because of the rebasing. How would you do that? Rather create another branch and PR? I mean, I would've deleted my feature branch anyway later...

**Comment by zormit** [comment]
haha now I messed it up. A new pull request is #4.

**Comment by craffel** [comment]
No worries.  If rebasing didn't work, one way you could potentially do it would have been to `git reset --hard upstream/master` and then cherry-picked the commits from reflog.

**Pull request closed without merging**
